name: Build JCEF on Windows amd64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # with:
          # repository: 'JetBrains/jcef'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '16'
          msbuild-architecture: x64

      - name: Install dependencies
        run: |
          choco install ant --version=1.10.14
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          echo "ANT_HOME=C:\ProgramData\chocolatey\lib\ant\apache-ant-1.10.14" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "JAVA_HOME=${env:JAVA_HOME}" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "VS160COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "JCEF_CMAKE=C:\Program Files\CMake\bin" | Out-File -Append -FilePath $env:GITHUB_ENV
      - name: Build JCEF
        run: |
          cd .\jb\tools\windows
          cmd /c build.bat all x86_64
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jcef_win_x86_64
          path: jcef_win_x86_64.tar.gz

